import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { readFile } from "node:fs/promises";
import path from "node:path";

// Idempotent seed: re-running won't create duplicates. Reads
// ADMIN_SEED_EMAIL and ADMIN_SEED_PASSWORD from .env. Both required.
//
// Run with:  npm run db:seed

const prisma = new PrismaClient();

async function main() {
  const email = process.env.ADMIN_SEED_EMAIL;
  const password = process.env.ADMIN_SEED_PASSWORD;

  if (!email || !password) {
    throw new Error(
      "ADMIN_SEED_EMAIL and ADMIN_SEED_PASSWORD must be set in .env",
    );
  }

  const passwordHash = await bcrypt.hash(password, 12);

  const admin = await prisma.adminUser.upsert({
    where: { email },
    update: { passwordHash },
    create: {
      email,
      passwordHash,
      name: "Admin",
      role: "admin",
    },
  });

  // eslint-disable-next-line no-console
  console.log(`✓ Admin upserted: ${admin.email} (id=${admin.id})`);

  // Ensure the Settings singleton exists so /admin/settings always has a row.
  await prisma.settings.upsert({
    where: { id: "default" },
    update: {},
    create: { id: "default" },
  });
  // eslint-disable-next-line no-console
  console.log("✓ Settings(default) ensured");

  // Seed a default About body so the public /about page renders something
  // immediately. Re-running won't overwrite admin edits because we use
  // create-only (`update: {}`).
  await prisma.siteContent.upsert({
    where: { key: "about" },
    update: {},
    create: {
      key: "about",
      content: {
        body:
          "Студия пирсинга, где украшения подбираются под вас, а каждое решение остаётся за вами.\n\n" +
          "Мы внимательны к каждой детали — от подготовки до ухода. Расскажите, какой образ вы себе представляете, и мы вместе подберём решение.",
      },
    },
  });
  // eslint-disable-next-line no-console
  console.log("✓ SiteContent(about) ensured");

  // ─── Jewelry categories ───
  const categories: Array<{ slug: string; name: string; order: number }> = [
    { slug: "earrings", name: "Серьги", order: 0 },
    { slug: "helix", name: "Хеликс", order: 1 },
    { slug: "septum", name: "Септум", order: 2 },
    { slug: "labret", name: "Лабрет", order: 3 },
    { slug: "nostril", name: "Нос", order: 4 },
    { slug: "eyebrow", name: "Бровь", order: 5 },
    { slug: "navel", name: "Пупок", order: 6 },
    { slug: "nipple", name: "Сосок", order: 7 },
  ];
  await Promise.all(
    categories.map((c) =>
      prisma.jewelryCategory.upsert({
        where: { slug: c.slug },
        update: { name: c.name, order: c.order },
        create: c,
      }),
    ),
  );
  // eslint-disable-next-line no-console
  console.log(`✓ JewelryCategory: ${categories.length} ensured`);

  // ─── Anchor points ───
  // Sourced from `prisma/seed-data/anchors.json`, which is generated by the
  // Blender pipeline (see `scripts/blender/` and README "Body model pipeline").
  // Coordinates are in body.glb local space (Y-up), tuned against the real GLB.
  // Re-running seeds re-tunes all 29 anchors from the JSON; admin tweaks are
  // not preserved (this is intentional while v1 is iterating).

  type Vec3 = { x: number; y: number; z: number };
  type CameraPreset = {
    name: string;
    position: Vec3;
    target: Vec3;
    fov: number;
  };
  type Place =
    | "EAR"
    | "NOSE"
    | "LIPS"
    | "EYEBROW"
    | "TONGUE"
    | "NIPPLE"
    | "NAVEL"
    | "HIP"
    | "ANKLE";
  type Side = "L" | "R" | "CENTER";

  interface AnchorSeed {
    slug: string;
    name: string;
    place: Place;
    side: Side;
    position: Vec3;
    rotation: Vec3;
    cameraPresets: CameraPreset[];
  }

  const anchorsPath = path.join(
    process.cwd(),
    "prisma",
    "seed-data",
    "anchors.json",
  );
  const raw = await readFile(anchorsPath, "utf-8");
  const parsed = JSON.parse(raw) as Array<{
    slug: string;
    name: string;
    place: Place;
    side: Side;
    position: Vec3;
    rotation: Vec3;
    cameraPresets?: CameraPreset[];
  }>;
  const anchors: AnchorSeed[] = parsed.map((a) => ({
    slug: a.slug,
    name: a.name,
    place: a.place,
    side: a.side,
    position: a.position,
    rotation: a.rotation,
    cameraPresets: a.cameraPresets ?? [],
  }));

  await Promise.all(
    anchors.map((a) =>
      prisma.anchorPoint.upsert({
        where: { slug: a.slug },
        // Always re-tune from the seed for now. When we move to a real GLB
        // and admin tuning UI, this will switch back to "preserve admin edits".
        update: {
          name: a.name,
          place: a.place,
          side: a.side,
          position: a.position,
          rotation: a.rotation,
          cameraPresets: a.cameraPresets,
        },
        create: a,
      }),
    ),
  );
  // eslint-disable-next-line no-console
  console.log(`✓ AnchorPoint: ${anchors.length} ensured`);

  // ─── Jewelry (parametric Blender pipeline) ───
  // Source of truth: `prisma/seed-data/jewelry.json` (manifest, committed).
  // Blob URLs:       `prisma/seed-data/jewelry-uploads.json` (slug -> {blobUrl, hash, ...},
  //                  produced by `npm run jewelry:upload` after Blender exports).
  // Pipeline overview: docs/14-jewelry-pipeline.md (added in Task 6).

  type MaterialColor =
    | "titanium"
    | "gold-585"
    | "rose-gold-585"
    | "black-pvd";

  interface JewelrySeed {
    slug: string;
    name: string;
    categorySlug: string;
    shape: string;
    /** Per-shape Blender params; not used by the seed. */
    params: Record<string, unknown>;
    material: string;
    materialColor: MaterialColor;
    gauge: number | null;
    size: number | null;
    color: string | null;
    stones: string | null;
    price: number;
    inStock: number;
    featured: boolean;
    anchorSlugs: string[];
  }

  interface JewelryUpload {
    blobUrl: string;
    hash: string;
    size: number;
    uploadedAt: string;
    /** Optional thumbnail URL — populated only when render_thumbnails ran. */
    thumbUrl?: string;
  }

  const jewelryManifestPath = path.join(
    process.cwd(),
    "prisma",
    "seed-data",
    "jewelry.json",
  );
  const jewelryUploadsPath = path.join(
    process.cwd(),
    "prisma",
    "seed-data",
    "jewelry-uploads.json",
  );

  const jewelryManifestRaw = await readFile(jewelryManifestPath, "utf-8");
  const jewelryUploadsRaw = await readFile(jewelryUploadsPath, "utf-8");
  const jewelryManifest: JewelrySeed[] = JSON.parse(jewelryManifestRaw);
  const jewelryUploads: Record<string, JewelryUpload> =
    JSON.parse(jewelryUploadsRaw);

  // Look up category + anchor ids in one pass each so the loop is O(N).
  const categoryRows = await prisma.jewelryCategory.findMany({
    select: { id: true, slug: true },
  });
  const categoryIdBySlug = new Map(categoryRows.map((c) => [c.slug, c.id]));

  const anchorRows = await prisma.anchorPoint.findMany({
    select: { id: true, slug: true },
  });
  const anchorIdBySlug = new Map(anchorRows.map((a) => [a.slug, a.id]));

  let jewelryCreated = 0;
  let jewelryUpdated = 0;
  for (const piece of jewelryManifest) {
    const categoryId = categoryIdBySlug.get(piece.categorySlug);
    if (!categoryId) {
      // eslint-disable-next-line no-console
      console.warn(
        `! Jewelry "${piece.slug}": unknown categorySlug "${piece.categorySlug}", skipping`,
      );
      continue;
    }

    const anchorIds = piece.anchorSlugs
      .map((s) => {
        const id = anchorIdBySlug.get(s);
        if (!id) {
          // eslint-disable-next-line no-console
          console.warn(
            `! Jewelry "${piece.slug}": unknown anchorSlug "${s}", skipping that anchor`,
          );
        }
        return id;
      })
      .filter((id): id is string => Boolean(id));

    const upload = jewelryUploads[piece.slug];
    const glbUrl = upload?.blobUrl ?? null;
    const glbThumbUrl = upload?.thumbUrl ?? null;
    // Pieces without a built .glb stay DRAFT (invisible on /catalog);
    // the upload step + a re-seed flips them to PUBLISHED.
    const status = glbUrl ? "PUBLISHED" : "DRAFT";

    const existing = await prisma.jewelry.findUnique({
      where: { slug: piece.slug },
      select: { id: true },
    });

    const data = {
      name: piece.name,
      categoryId,
      material: piece.material,
      gauge: piece.gauge,
      size: piece.size,
      color: piece.color,
      stones: piece.stones,
      price: piece.price,
      inStock: piece.inStock,
      featured: piece.featured,
      glbUrl,
      glbThumbUrl,
      status: status as "PUBLISHED" | "DRAFT",
    };

    if (existing) {
      await prisma.jewelry.update({
        where: { slug: piece.slug },
        data: {
          ...data,
          anchors: { set: anchorIds.map((id) => ({ id })) },
        },
      });
      jewelryUpdated += 1;
    } else {
      await prisma.jewelry.create({
        data: {
          ...data,
          slug: piece.slug,
          photos: [],
          anchors: { connect: anchorIds.map((id) => ({ id })) },
        },
      });
      jewelryCreated += 1;
    }
  }
  // eslint-disable-next-line no-console
  console.log(
    `✓ Jewelry: ${jewelryManifest.length} ensured (${jewelryCreated} created, ${jewelryUpdated} updated)`,
  );
}

main()
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
